[tool.autopep8]
max_line_length = 120
ignore = "E203,E501,W503"
in-place = true
recursive = true
aggressive = 3

[tool.black]
line-length = 120
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 120
py_version = 311
known_third_party = [
    "aiofile",
    "aiohttp",
    "aiohttp_client_cache",
    "aiopath",
    "anyio",
    "apscheduler",
    "apsw",
    "asyncpg",
    "asyncspotify",
    "asyncstdlib",
    "brotli",
    "cached_property",
    "discord",
    "deepdiff",
    "expiringdict",
    "humanize",
    "iso8601",
    "packaging",
    "piccolo",
    "platformdirs",
    "psutil",
    "pytz",
    "yaml",
    "red_commons",
    "redis",
    "rich",
    "tabulate",
    "typing_extensions",
    "ujson",
    "uvloop"

]
known_first_party = [
    "pylav",
]
known_local_folder = [
    "audio",
    "plconfig",
    "pleffects",
    "pleq",
    "pllocal",
    "plmanagednode",
    "plmigrator",
    "plnodes",
    "plnotifier",
    "plplaylists",
    "plradio",
    "plutils"
]
