name: automerge
on:
    pull_request:
        types:
        -   labeled
        -   unlabeled
        -   synchronize
        -   opened
        -   edited
        -   ready_for_review
        -   reopened
        -   unlocked
    pull_request_review:
        types:
        -   submitted
    check_suite:
        types:
        -   completed
    status: {}
jobs:
    automerge:
        runs-on: ubuntu-latest
        steps:
        -   id: automerge
            name: automerge
            uses: pascalgn/automerge-action@v0.15.3
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                MERGE_FORKS: 'false'
                MERGE_METHOD: squash
                UPDATE_METHOD: rebase
                MERGE_REQUIRED_APPROVALS: '0'
                MERGE_METHOD_LABELS: automerge=merge,autosquash=automerge
                MERGE_COMMIT_MESSAGE: '[skip-ci] chore: update translations'
                MERGE_REMOVE_LABELS: automerge
                MERGE_LABELS: automerge
                MERGE_FILTER_AUTHOR: github-actions
                MERGE_METHOD_LABEL_REQUIRED: true
                MERGE_DELETE_BRANCH: true
